version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    volumes:
      - ..:/workspaces/demo:cached
      - jsc-node_modules:/workspace/node_modules
    tmpfs:
      - /workspace/dist:rw,noexec,nosuid,size=10M
    container_name: jsc-express
    command: "sleep infinity"
    depends_on:
      - redis-stack
  
  redis-stack:
    image: redis/redis-stack:latest
    volumes:
     - jsc-redis-data:/data
    expose:
      - 6379
    ports:
      - 8001
    restart: on-failure

volumes:
 jsc-redis-data:
 jsc-node_modules: